name: attedance
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    


  cupertino_icons: ^1.0.2
  image_picker: ^1.0.4
  intl: ^0.18.1
  firebase_core: ^2.22.0
  firebase_auth: ^4.14.0

  flutter_polyline_points: ^2.0.0
  google_maps_flutter: ^2.5.0
  location: ^5.0.3
  flutter_svg: ^2.0.9
  datetime_picker_formfield_new: ^2.1.0
  dotted_border: ^2.1.0
  file_picker: ^6.1.1
  iconsax: ^0.0.8
  map_camera_flutter: ^0.0.4
  latlong2: ^0.9.0
  convex_bottom_bar: ^3.2.0
  dropdown_search: ^5.0.6
  buttons_tabbar: ^1.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1


flutter:

  uses-material-design: true

  assets:
    - assets/images/pro1.jpg
    - assets/images/logoptsos.png


  fonts:
    - family: SometypeMono
      fonts:
        - asset: assets/fonts/SometypeMono-Bold.ttf
        - asset: assets/fonts/SometypeMono-Italic.ttf
        - asset: assets/fonts/SometypeMono-Regular.ttf
        - asset: assets/fonts/SometypeMono-SemiBoldItalic.ttf
        
